#!/bin/bash

www="`echo $1 | awk -F . '{print $1}'`"
subzone="`echo $1 | awk -F . '{print $2}'`"

check="`cat /etc/bind/zones/scriptzones/db.$subzone.tuan-temmerman.sb.uclllabs.be | grep -E '[0-9].[0-9].[0-9].[0-9]' | awk '{print $1}'`"
echo "$check 1"
echo "$subzone 2"

if [ $www != $check ]; then
	exit 1
else
	echo "$1 3"

	if [ -e "/etc/bind/zones/scriptzones/db.$subzone.tuan-temmerman.sb.uclllabs.be" ]; then

		mkdir /var/www/$1
		echo "werkt dit? $1"
		touch /var/www/$1/index.html

		echo "welcome $1" > /var/www/$1/index.html

		touch /etc/apache2/sites-available/$1.conf

		echo "
		<VirtualHost *:80>
			ServerAdmin r0705046@student.ucll.be
		       	ServerName $1
		      	DocumentRoot /var/www/$1
		     	LogLevel info
		       	ErrorLog "${APACHE_LOG_DIR}"/$1-error.log
		       	CustomLog "${APACHE_LOG_DIR}"/$1-access.log combined
		</VirtualHost>" > /etc/apache2/sites-available/$1.conf

		a2ensite $1.conf
		systemctl reload apache2

		else
		   	exit 1
	fi
fi
