#!/bin/bash

if [ -e "/etc/bind/zones/scriptzones/db.$1" ]; then

mkdir "/var/www/$1"

echo "
<VirtualHost *:80>
	ServerAdmin r0705046@student.ucll.be
	ServerName $1
	DocumentRoot /var/www/$1
	ErrorLog ${APACHE_LOG_DIR}/$1-error.log
	CustomLog ${APACHE_LOG_DIR}/$1-access.log combined
	</VirtualHost>" > /etc/apache2/sites-available/$1.conf

touch "/var/www/$1/index.html"

echo "Welcome $1" > /var/www/$1/index.html

a2ensite $1.conf
systemctl reload apache2

else
	exit 1
fi
